#!/usr/bin/env bash
# error 404

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i "24i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page\n" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i "25i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
